server:
  port: 9001
spring:
  application:
    name: spring-cloud-eureka-client-review
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5050/eureka
    prefer-same-zone-eureka: true      
  instance:
    preferIpAddress: true