spring:
  application:
    name: spring-cloud-eureka-client-info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    prefer-same-zone-eureka: true
  instance:
    preferIpAddress: true